## Library Importation

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import dtale

C:\Users\user\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.8' currently installed).
  warnings.warn(msg, UserWarning)
C:\Users\user\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10051] A socket operation was attempted to an unreachable network
  % (host, default, e), RuntimeWarning)

## Data importation

In [2]:
Telco=pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
pd.set_option('display.max_columns', None) #show all columns
Telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Understanding the Dataset

In [3]:
Telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

It should be noted here that there is no missing values in the dataset.

However, some column are not in the right datatype, to correct this, dtale library will be used

In [4]:
dtale.show()

2023-08-01 18:57:09,589 - ERROR    - Exception occurred while processing request: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 112, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 2565, in get_data
    curr_dtypes = [c["name"] for c in global_state.get_dtypes(data_id)]
TypeError: 'NoneType' object is not iterable
C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py:2004: FutureWarning:

The default value of regex will change from True to False in a future version.

2023-08-01 19:06:26,659 - ERROR    - Exception occurred while processing request: local variable 'replace' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 112, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 1878, in build_replacement
    output = builder.build_replacements()
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\column_replacements.py", line 31, in build_replacements
    return self.builder.build_column(global_state.get_data(self.data_id))
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\column_replacements.py", line 162, in build_column
    replacements[value] = replace
UnboundLocalError: local variable 'replace' referenced before assignment
2023-08-01 19:06:54,101 - ERROR    - Exception occurred while processing request: local variable 'replace' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 112, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 1878, in build_replacement
    output = builder.build_replacements()
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\column_replacements.py", line 31, in build_replacements
    return self.builder.build_column(global_state.get_data(self.data_id))
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\column_replacements.py", line 162, in build_column
    replacements[value] = replace
UnboundLocalError: local variable 'replace' referenced before assignment
2023-08-01 19:09:05,628 - ERROR    - Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 112, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py", line 1923, in test_filter
    global_state.get_context_variables(data_id),
  File "C:\Users\user\Anaconda3\lib\site-packages\dtale\query.py", line 92, in run_query
    engine=engine,
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object
C:\Users\user\Anaconda3\lib\site-packages\dtale\views.py:2004: FutureWarning:

The default value of regex will change from True to False in a future version.

C:\Users\user\Anaconda3\lib\site-packages\dtale\dash_application\charts.py:4113: UserWarning:

No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 4113 of the file C:\Users\user\Anaconda3\lib\site-packages\dtale\dash_application\charts.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

## Summary of the variuos data cleaning process carried out

(1) Senior Citizen: This column was converted to string then replace '0' with "No" and '1' with "Yes"

(2) Total Charges: This column was converted to float and the missing values (as a result of 'white space') was replaced with zero, futher findings reveal that these missing values has a tenure of 0 month which means they are new customers.

Since our dataset is clean, we can now proceed to the analysis to understand why the Telco Organization loses their customers and recommend necessary solution. The visualization will be done in Tableau

## Predicting the Churning of the Customers based on the Factors given

In [16]:
# Importing the cleaned Dataset
Clean_Telco=pd.read_csv('Clean Dataset.csv')
pd.set_option('display.max_columns', None) #show all columns
Clean_Telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
#importing the libraries needed
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import StandardScaler

# Import libraries of statsmodels for logistic regression based binary clasification
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels. api as smf
from statsmodels.formula.api import logit

In [13]:
# Split data into train and test data
train_data, test_data=train_test_split(Clean_Telco,test_size=0.30)
train_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2872,8148-NLEGT,Female,No,Yes,Yes,42,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Electronic check,22.95,1014.25,No
5598,6051-PTVNS,Female,No,Yes,Yes,55,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.15,998.10,No
5488,7856-GANIL,Male,Yes,Yes,No,45,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,No,One year,Yes,Bank transfer (automatic),98.70,4525.80,No
3969,2920-RNCEZ,Male,No,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.95,69.95,No
3508,2368-GAKKQ,Female,No,No,No,70,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),113.65,7939.25,No

In [17]:
#Definnig the formula to perform classification based on input features
formula='Churn~gender+SeniorCitizen+Partner+Dependents+tenure+PhoneService+MultipleLines+InternetService+OnlineSecurity+OnlineBackup+DeviceProtection+TechSupport+StreamingTV+StreamingMovies+Contract+PaperlessBilling+PaymentMethod+MonthlyCharges+TotalCharges'

In [18]:
#Defining the logistic regression Model
model=logit(formula = formula, data= train_data).fit()

ValueError: endog has evaluated to an array with multiple columns that has shape (4930, 2). This occurs when the variable converted to endog is non-numeric (e.g., bool or str).